This notebook is used to develop a function (based on numpy) to be able to maximize two arrays over a specified axis. The motivation of this is to solve the problem of given two vector fields with shape, say (Nsize, Nsize, Nsize, 4), how we can get a output vector field such that at each point is the vector field value with largest third component of the two fields. (e.g. at some point, vector value [1,2,3,4] is selected over [4,3,2,1].)

In [4]:
# maximum?
import numpy as np

data1 = np.random.rand(2,2,4)
data2 = np.random.rand(2,2,4)
print('data1: ', data1, '\n')
print('data2: ', data2, '\n')

truearr = np.full((2, 2, 3), False)
falsearr = np.full((2, 2, 1), True)
boolarr = np.concatenate((truearr, falsearr), axis=2)

output = np.maximum(data1, data2, where=boolarr)
print('output: ', output)
# issue : except for maximizing the last component, the output take the rest of 
# value from data2.

data1:  [[[0.65863993 0.76215546 0.589668   0.13137179]
  [0.3098471  0.46028451 0.73932358 0.89791256]]

 [[0.18609699 0.55516433 0.32283561 0.01436058]
  [0.56884293 0.2009529  0.47864858 0.08242949]]] 

data2:  [[[0.95411302 0.21031596 0.74669867 0.66262938]
  [0.50690708 0.15313426 0.12008016 0.48399362]]

 [[0.7793065  0.68587063 0.16996605 0.89995965]
  [0.98776651 0.80412389 0.48414322 0.24180389]]] 

output:  [[[0.95411302 0.21031596 0.74669867 0.66262938]
  [0.50690708 0.15313426 0.12008016 0.89791256]]

 [[0.7793065  0.68587063 0.16996605 0.89995965]
  [0.98776651 0.80412389 0.48414322 0.24180389]]]


In [16]:
# ufunc?
import numpy as np

data1 = np.random.rand(2,2,4)
data2 = np.random.rand(2,2,4)
print('data1: ', data1, '\n')
print('data2: ', data2, '\n')

boolarr = data1[:,:,3] > data2[:,:,3]
boolarr = np.stack((boolarr, boolarr, boolarr, boolarr), 2) # this is fucking ugly
print(boolarr.shape)
print('boolarr: ', boolarr, '\n')

output = np.where(boolarr, data1, data2)
print('output: ', output)

data1:  [[[0.2867273  0.72425837 0.27850917 0.38906279]
  [0.17551568 0.97517672 0.48734197 0.9590225 ]]

 [[0.89070108 0.07544138 0.02347651 0.19702417]
  [0.93202332 0.87696868 0.23866475 0.32672092]]] 

data2:  [[[0.0673769  0.26580564 0.24937553 0.46792389]
  [0.39985757 0.4290896  0.5064146  0.03504068]]

 [[0.86458013 0.81729199 0.53836042 0.45677154]
  [0.8233393  0.68440695 0.19832134 0.59250019]]] 

(2, 2, 4)
boolarr:  [[[False False False False]
  [ True  True  True  True]]

 [[False False False False]
  [False False False False]]] 

output:  [[[0.0673769  0.26580564 0.24937553 0.46792389]
  [0.17551568 0.97517672 0.48734197 0.9590225 ]]

 [[0.86458013 0.81729199 0.53836042 0.45677154]
  [0.8233393  0.68440695 0.19832134 0.59250019]]]
