In [5]:
import numpy as np

arr = np.random.rand(3,5)
print(arr)

[[0.35436721 0.87870417 0.34496612 0.55249924 0.69641004]
 [0.83564971 0.16177692 0.68582934 0.3489693  0.01049571]
 [0.56665267 0.56099012 0.34671766 0.61849921 0.13011441]]


In [6]:
import test_module as test

In [7]:
import time

print('C++:')
start_time = time.perf_counter_ns()
print('Answer:', test.echo2darray(arr))
print('Time:', (time.perf_counter_ns() - start_time) / 1e9, 's')

C++:
Answer: [[0.35436721 0.87870417 0.34496612 0.55249924 0.69641004]
 [0.83564971 0.16177692 0.68582934 0.3489693  0.01049571]
 [0.56665267 0.56099012 0.34671766 0.61849921 0.13011441]]
Time: 0.000429227 s
(0.354367, 0.878704, 0.344966, 0.552499, 0.69641)
(0.83565, 0.161777, 0.685829, 0.348969, 0.0104957)
(0.566653, 0.56099, 0.346718, 0.618499, 0.130114)
